name: Python Application Test

# Define when this workflow should run
on:
  # Run tests on push to the 'main' branch and on pull requests
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Define the job that GitHub Actions will run
jobs:
  test:
    # This job will run on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # Steps of the job
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the appropriate Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run tests
    - name: Run tests
      run: |
        pytest --maxfail=5 --disable-warnings  # Run pytest
